name: 🐛 Bug Report (Agent Ready)
description: Report a bug with full context for AI agents to investigate
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report — Truth-First Format
        
        This template helps AI agents (and humans) understand and fix bugs quickly.
        
        **Prime Rule:** Only report what you can prove. No guesses.

  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: One-line description of the bug
      placeholder: "Device flash fails with 'USB device not found' error despite device being connected"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Exact steps to reproduce the bug
      placeholder: |
        1. Connect device via USB
        2. Run `npm run dev`
        3. Navigate to http://localhost:5173
        4. Click "Flash Device"
        5. Select firmware file
        6. Click "Start Flash"
        7. Error appears: "USB device not found"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: "Device should be detected and firmware flash should begin"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Error message 'USB device not found' appears, flash does not start"
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence (Logs, Screenshots, Error Messages)
      description: Paste relevant logs, error messages, or add screenshots
      placeholder: |
        ```
        Error: USB device not found
            at Device.scan (src/lib/device.ts:45)
            at FlashButton.onClick (src/components/FlashButton.tsx:23)
        ```
      render: shell
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your system details
      placeholder: |
        - OS: Ubuntu 22.04
        - Node: v20.10.0
        - npm: 10.2.0
        - Browser: Chrome 120
        - Device: Samsung Galaxy S10 (Serial: ABC123)
      value: |
        - OS: 
        - Node: 
        - npm: 
        - Browser: 
        - Device:
    validations:
      required: true

  - type: dropdown
    id: regression
    attributes:
      label: Is this a regression?
      description: Did this work in a previous version?
      options:
        - "No - Never worked"
        - "Yes - Worked in previous version"
        - "Unknown"
    validations:
      required: true

  - type: input
    id: last_worked
    attributes:
      label: Last Known Working Version (if regression)
      description: If this is a regression, what version last worked?
      placeholder: "v2.1.0"

  - type: textarea
    id: workaround
    attributes:
      label: Workaround (if known)
      description: Is there a temporary workaround?
      placeholder: "Running with sudo works: `sudo npm run dev`"

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How severe is this bug?
      options:
        - "Critical - Blocks all work"
        - "High - Blocks major functionality"
        - "Medium - Workaround available"
        - "Low - Minor inconvenience"
    validations:
      required: true

  - type: checkboxes
    id: validation
    attributes:
      label: Pre-Submission Checklist
      description: Verify these before submitting
      options:
        - label: I have searched existing issues (this is not a duplicate)
          required: true
        - label: I have provided exact steps to reproduce
          required: true
        - label: I have included error logs or screenshots
          required: true
        - label: I have specified my environment details
          required: true
        - label: I have tested on the latest version
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: "This started happening after upgrading to Ubuntu 22.04. Worked fine on Ubuntu 20.04."
